<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../lib/core/datasource_abstraction.php';

/**
 * Test class for csvTimeSeries.
 * Generated by PHPUnit on 2011-05-04 at 11:49:52.
 */
class csvTimeSeriesTest extends PHPUnit_Framework_TestCase {

    /**
     * @var csvTimeSeries
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new csvTimeSeries;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testGetNearestRealFacets().
     */
    public function testGetNearestRealFacets() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetInterpolatedValueFromFacet().
     */
    public function testGetInterpolatedValueFromFacet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetRealValueFromFacet().
     */
    public function testGetRealValueFromFacet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testIsRealFacet().
     */
    public function testIsRealFacet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetPalaeoTime().
     */
    public function testGetPalaeoTime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
?>
