<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../lib/core/datasource_abstraction.php';

/**
 * Test class for dataSet.
 * Generated by PHPUnit on 2011-05-04 at 11:49:52.
 */
class dataSetTest extends PHPUnit_Framework_TestCase {

    /**
     * @var dataSet
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new dataSet;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testGetDataSetDescription().
     */
    public function testGetDataSetDescription() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetBlankScalar().
     */
    public function testGetBlankScalar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetInterpolatedValueFromFacet().
     */
    public function testGetInterpolatedValueFromFacet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
?>
