<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../lib/core/magic_glue.php';

/**
 * Test class for EnvironmentalRecord.
 * Generated by PHPUnit on 2011-05-07 at 15:36:43.
 */
class EnvironmentalRecordTest extends PHPUnit_Framework_TestCase {

    /**
     * @var EnvironmentalRecord
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new EnvironmentalRecord;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
?>
