<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../lib/core/palaeotime.class.php';

/**
 * Test class for palaeoTime.
 * Generated by PHPUnit on 2011-06-22 at 07:19:45.
 */
class palaeoTimeTest extends PHPUnit_Framework_TestCase {

    /**
     * @var palaeoTime
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new palaeoTime (1000);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testGetYearsBp().
     */
    public function testGetYearsBp() {
        $years = array (-9919,-101,-1,-0,0.00,1,100);
        echo $this->object->setYearsBp(777) . "\n";
        echo $this->object->setYearsBp(777) . "\n";
        
        foreach ($years as $ybp) {
            echo $this->object->setYearsBp($ybp) . "<\n";
            $this->assertEquals ($ybp, $this->object->getYearsBp(), "YBP in != YBP out");
        }
    }

    /**
     * @todo Implement testSetYearsBp().
     */
    public function testSetYearsBp() {
        $years = array (-100,-1,-0,0.00,1,100);
        foreach ($years as $ybp) {
            $this->object->setYearsBp($ybp);
            //print_r ($this->object->timeScalar);
        }
    }

    /**
     * @todo Implement testDistanceTo().
     */
    public function testDistanceTo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testInit().
     */
    public function testInit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement test_bootstrap().
     */
    public function test_bootstrap() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
?>
