<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../lib/core/scalars.php';

/**
 * Test class for scalarFactory.
 * Generated by PHPUnit on 2011-06-14 at 15:45:57.
 */
class scalarFactoryTest extends PHPUnit_Framework_TestCase {

    /**
     * @var scalarFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new scalarFactory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement test_getNowBp().
     */
    public function test_getNowBp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement test_getAdBp().
     */
    public function test_getAdBp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSecsPerYear().
     */
    public function testSecsPerYear() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSecsPerDay().
     */
    public function testSecsPerDay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     
     */
    public function testMakeYearsBp() {
        // Remove the following lines when you implement this test.
        $a = scalarFactory::makeYearsBp(0);
        $this->assertEquals ($a->getValue(), scalarFactory::yearsWBp, "0bp doesn't equal " . scalarFactory::yearsWBp);
    }

    /**
     * @todo Implement testMakeKelvin().
     */
    public function testMakeKelvin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testMakeKelvinAnomaly().
     */
    public function testMakeKelvinAnomaly() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testMakeCentigradeAbs().
     */
    public function testMakeCentigradeAbs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testMakeKilometres().
     */
    public function testMakeKilometres() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testMakeMetres().
     */
    public function testMakeMetres() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testMakeMolesPerYear().
     */
    public function testMakeMolesPerYear() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testMakeMolesPerSecond().
     */
    public function testMakeMolesPerSecond() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testMakeJoulesPerMole().
     */
    public function testMakeJoulesPerMole() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testMakeKilojoulesPerMole().
     */
    public function testMakeKilojoulesPerMole() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testMakeAU().
     */
    public function testMakeAU() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testMakeThermalDiffusivity().
     */
    public function testMakeThermalDiffusivity() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testMakeDays().
     */
    public function testMakeDays() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testMakeYears().
     */
    public function testMakeYears() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testMakeSeconds().
     */
    public function testMakeSeconds() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testMake10CThermalYears().
     */
    public function testMake10CThermalYears() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testMake10CThermalSeconds().
     */
    public function testMake10CThermalSeconds() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
?>
